[WIP] Update the remote-signer to be ubuntu arm64 based
midl-dev/tezos-remote-signer-os pull request #10
Opened 2021-05-18 21:48 UTC by puppetninja

2021-05-26 04:20 UTC, nicolasochem requested changes
I tried and it works great! Thank you. Just a few readme fixes are in order.

2021-05-26 04:20 UTC, nicolasochem commented on README.md
> +In bootstrap procedure, add the `tezos` user, disable ssh password access, enable public-key ssh authentication as `tezos` user with the public key that is in your `~/.ssh` folder.
This sounds like you have to do it, but ansible does it for you. Replace with "The bootstrap procedure will add the tezos user etc..."

2021-05-26 04:20 UTC, nicolasochem commented on README.md
really? It looks like the last step rebooted it.

2021-05-26 16:12 UTC, puppetninja commented on README.md
yes, I provide the reason in the new commit, ubuntu is the user to execute the reboot, so it would be cached by sshd even after the reboot

2021-05-27 04:52 UTC, nicolasochem approved these changes

2021-05-27 04:52 UTC, merged